### ISSUE TITLE
"Access denied" error message

### ISSUE THREAD

**Issue by bondskin** [donhector/ubiquiti-drawio#1]
Hi,

when I am trying to retrieve https://github.com/donhector/ubiquiti-drawio/raw/main/Ubiquiti.xml, I'll get the following "Access denied" error message in draw.io (MacOS, 20.3.0).

Is this known?

<img width="774" alt="SCR-20221119-dhp" src="https://user-images.githubusercontent.com/55050117/202842715-e4619ea2-e6e2-40b1-8563-d6cd045b7233.png">

**Comment by donhector** [comment]
Hi, I'm not aware of any errors and I don't have a Mac to repro. Sorry!
